// <auto-generated />
using System;
using API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace API.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.6");

            modelBuilder.Entity("API.Entites.Bio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Key")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Bio");
                });

            modelBuilder.Entity("API.Entites.ChapterAttributes", b =>
                {
                    b.Property<int>("ChapterAttributesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Chapter")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("FK_ChapterData_Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Hash")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PublishAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.Property<string>("TranslatedLanguage")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Volume")
                        .HasColumnType("TEXT");

                    b.HasKey("ChapterAttributesId");

                    b.ToTable("ChapterAttributes");
                });

            modelBuilder.Entity("API.Entites.ChapterData", b =>
                {
                    b.Property<int>("ChapterDataId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AttributesChapterAttributesId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ChapterId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("ChapterRead")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FK_MangaChapter_Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .HasColumnType("TEXT");

                    b.HasKey("ChapterDataId");

                    b.HasIndex("AttributesChapterAttributesId");

                    b.ToTable("ChapterData");
                });

            modelBuilder.Entity("API.Entites.ChapterId", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ChaptersReadId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ReadId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ChaptersReadId");

                    b.ToTable("ChapterId");
                });

            modelBuilder.Entity("API.Entites.ChapterRelationship", b =>
                {
                    b.Property<int>("ChapterRelationshipId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("FK_MangaChapter_Id")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MangaChapterId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RelationshipId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .HasColumnType("TEXT");

                    b.HasKey("ChapterRelationshipId");

                    b.HasIndex("MangaChapterId");

                    b.ToTable("ChapterRelationship");
                });

            modelBuilder.Entity("API.Entites.ChaptersRead", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Result")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ChaptersReads");
                });

            modelBuilder.Entity("API.Entites.CoverArt", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Volume")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CoverArts");
                });

            modelBuilder.Entity("API.Entites.Manga", b =>
                {
                    b.Property<int>("MangaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DataMangaDataId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FK_MangaCollection_Id")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MangaChaptersId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MangaCollectionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Result")
                        .HasColumnType("TEXT");

                    b.HasKey("MangaId");

                    b.HasIndex("DataMangaDataId");

                    b.HasIndex("MangaChaptersId");

                    b.HasIndex("MangaCollectionId");

                    b.ToTable("Mangas");
                });

            modelBuilder.Entity("API.Entites.MangaAltTitle", b =>
                {
                    b.Property<int>("MangaAltTitleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AltTitle")
                        .HasColumnType("TEXT");

                    b.Property<int>("FK_MangaAttributes_Id")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MangaAttributesId")
                        .HasColumnType("INTEGER");

                    b.HasKey("MangaAltTitleId");

                    b.HasIndex("MangaAttributesId");

                    b.ToTable("MangaAltTitle");
                });

            modelBuilder.Entity("API.Entites.MangaAttributes", b =>
                {
                    b.Property<int>("MangaAttributesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContentRating")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("FK_MangaData_Id")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastChapter")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastVolume")
                        .HasColumnType("TEXT");

                    b.Property<int?>("MangaDescriptionId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MangaLinksMangaLinkId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OriginalLanguage")
                        .HasColumnType("TEXT");

                    b.Property<string>("PublicationDemographic")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .HasColumnType("TEXT");

                    b.Property<int?>("TitleMangaTitleId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("Year")
                        .HasColumnType("TEXT");

                    b.HasKey("MangaAttributesId");

                    b.HasIndex("MangaDescriptionId");

                    b.HasIndex("MangaLinksMangaLinkId");

                    b.HasIndex("TitleMangaTitleId");

                    b.ToTable("MangaAttributes");
                });

            modelBuilder.Entity("API.Entites.MangaChapter", b =>
                {
                    b.Property<int>("MangaChapterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DataChapterDataId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FK_MangaChapters_Id")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MangaChaptersId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Result")
                        .HasColumnType("TEXT");

                    b.HasKey("MangaChapterId");

                    b.HasIndex("DataChapterDataId");

                    b.HasIndex("MangaChaptersId");

                    b.ToTable("MangaChapter");
                });

            modelBuilder.Entity("API.Entites.MangaChapters", b =>
                {
                    b.Property<int>("MangaChaptersId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("FK_Manga_Id")
                        .HasColumnType("INTEGER");

                    b.HasKey("MangaChaptersId");

                    b.ToTable("MangaChapters");
                });

            modelBuilder.Entity("API.Entites.MangaCollection", b =>
                {
                    b.Property<int>("MangaCollectionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.HasKey("MangaCollectionId");

                    b.ToTable("MangaCollection");
                });

            modelBuilder.Entity("API.Entites.MangaData", b =>
                {
                    b.Property<int>("MangaDataId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("FK_Manga_Id")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MangaAttributesId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MangaId")
                        .HasColumnType("TEXT");

                    b.HasKey("MangaDataId");

                    b.HasIndex("MangaAttributesId");

                    b.ToTable("MangaData");
                });

            modelBuilder.Entity("API.Entites.MangaDescription", b =>
                {
                    b.Property<int>("MangaDescriptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int>("FK_MangaAttributes_Id")
                        .HasColumnType("INTEGER");

                    b.HasKey("MangaDescriptionId");

                    b.ToTable("MangaDescription");
                });

            modelBuilder.Entity("API.Entites.MangaLink", b =>
                {
                    b.Property<int>("MangaLinkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Amazon")
                        .HasColumnType("TEXT");

                    b.Property<string>("AniList")
                        .HasColumnType("TEXT");

                    b.Property<string>("AnimePlanet")
                        .HasColumnType("TEXT");

                    b.Property<string>("BookWalker")
                        .HasColumnType("TEXT");

                    b.Property<string>("EBookJP")
                        .HasColumnType("TEXT");

                    b.Property<string>("EngTL")
                        .HasColumnType("TEXT");

                    b.Property<int>("FK_MangaAttributes_Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Kitsu")
                        .HasColumnType("TEXT");

                    b.Property<string>("MAL")
                        .HasColumnType("TEXT");

                    b.Property<string>("MangaUpdates")
                        .HasColumnType("TEXT");

                    b.Property<string>("NovelUpdates")
                        .HasColumnType("TEXT");

                    b.Property<string>("Raw")
                        .HasColumnType("TEXT");

                    b.HasKey("MangaLinkId");

                    b.ToTable("MangaLink");
                });

            modelBuilder.Entity("API.Entites.MangaTag", b =>
                {
                    b.Property<int>("MangaTagId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("FK_MangaAttributes_Id")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MangaAttributesId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TagAttributesId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TagId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .HasColumnType("TEXT");

                    b.HasKey("MangaTagId");

                    b.HasIndex("MangaAttributesId");

                    b.HasIndex("TagAttributesId");

                    b.ToTable("MangaTag");
                });

            modelBuilder.Entity("API.Entites.MangaTitle", b =>
                {
                    b.Property<int>("MangaTitleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("FK_MangaAttributes_Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.HasKey("MangaTitleId");

                    b.ToTable("MangaTitle");
                });

            modelBuilder.Entity("API.Entites.MangaUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DataId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Result")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DataId");

                    b.ToTable("MangaUsers");
                });

            modelBuilder.Entity("API.Entites.Relationship", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("FK_Manga_Id")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MangaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RelationshipId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RelationshipType")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MangaId");

                    b.ToTable("Relationship");
                });

            modelBuilder.Entity("API.Entites.ScanlationGroup", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("LeaderId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LeaderId");

                    b.ToTable("ScanlationGroups");
                });

            modelBuilder.Entity("API.Entites.TagAttributes", b =>
                {
                    b.Property<int>("TagAttributesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("FK_MangaTag_Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Group")
                        .HasColumnType("TEXT");

                    b.Property<int?>("NameTagNameId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("TagAttributesId");

                    b.HasIndex("NameTagNameId");

                    b.ToTable("TagAttributes");
                });

            modelBuilder.Entity("API.Entites.TagName", b =>
                {
                    b.Property<int>("TagNameId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("FK_TagAttributes_Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("TagNameId");

                    b.ToTable("TagName");
                });

            modelBuilder.Entity("API.Entites.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("User");
                });

            modelBuilder.Entity("API.Entites.UserAttributes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("UserAttributes");
                });

            modelBuilder.Entity("API.Entites.UserData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AttributesId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AttributesId");

                    b.ToTable("UserData");
                });

            modelBuilder.Entity("API.Entites.UserRelationship", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("MangaId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .HasColumnType("TEXT");

                    b.Property<int?>("UserDataId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserDataId");

                    b.ToTable("UserRelationship");
                });

            modelBuilder.Entity("API.Entites.Bio", b =>
                {
                    b.HasOne("API.Entites.User", null)
                        .WithMany("Bio")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("API.Entites.ChapterData", b =>
                {
                    b.HasOne("API.Entites.ChapterAttributes", "Attributes")
                        .WithMany()
                        .HasForeignKey("AttributesChapterAttributesId");

                    b.Navigation("Attributes");
                });

            modelBuilder.Entity("API.Entites.ChapterId", b =>
                {
                    b.HasOne("API.Entites.ChaptersRead", null)
                        .WithMany("Data")
                        .HasForeignKey("ChaptersReadId");
                });

            modelBuilder.Entity("API.Entites.ChapterRelationship", b =>
                {
                    b.HasOne("API.Entites.MangaChapter", null)
                        .WithMany("Relationships")
                        .HasForeignKey("MangaChapterId");
                });

            modelBuilder.Entity("API.Entites.Manga", b =>
                {
                    b.HasOne("API.Entites.MangaData", "Data")
                        .WithMany()
                        .HasForeignKey("DataMangaDataId");

                    b.HasOne("API.Entites.MangaChapters", "MangaChapters")
                        .WithMany()
                        .HasForeignKey("MangaChaptersId");

                    b.HasOne("API.Entites.MangaCollection", null)
                        .WithMany("Mangas")
                        .HasForeignKey("MangaCollectionId");

                    b.Navigation("Data");

                    b.Navigation("MangaChapters");
                });

            modelBuilder.Entity("API.Entites.MangaAltTitle", b =>
                {
                    b.HasOne("API.Entites.MangaAttributes", null)
                        .WithMany("AltTitles")
                        .HasForeignKey("MangaAttributesId");
                });

            modelBuilder.Entity("API.Entites.MangaAttributes", b =>
                {
                    b.HasOne("API.Entites.MangaDescription", "MangaDescription")
                        .WithMany()
                        .HasForeignKey("MangaDescriptionId");

                    b.HasOne("API.Entites.MangaLink", "MangaLinks")
                        .WithMany()
                        .HasForeignKey("MangaLinksMangaLinkId");

                    b.HasOne("API.Entites.MangaTitle", "Title")
                        .WithMany()
                        .HasForeignKey("TitleMangaTitleId");

                    b.Navigation("MangaDescription");

                    b.Navigation("MangaLinks");

                    b.Navigation("Title");
                });

            modelBuilder.Entity("API.Entites.MangaChapter", b =>
                {
                    b.HasOne("API.Entites.ChapterData", "Data")
                        .WithMany()
                        .HasForeignKey("DataChapterDataId");

                    b.HasOne("API.Entites.MangaChapters", null)
                        .WithMany("results")
                        .HasForeignKey("MangaChaptersId");

                    b.Navigation("Data");
                });

            modelBuilder.Entity("API.Entites.MangaData", b =>
                {
                    b.HasOne("API.Entites.MangaAttributes", "MangaAttributes")
                        .WithMany()
                        .HasForeignKey("MangaAttributesId");

                    b.Navigation("MangaAttributes");
                });

            modelBuilder.Entity("API.Entites.MangaTag", b =>
                {
                    b.HasOne("API.Entites.MangaAttributes", null)
                        .WithMany("Tags")
                        .HasForeignKey("MangaAttributesId");

                    b.HasOne("API.Entites.TagAttributes", "TagAttributes")
                        .WithMany()
                        .HasForeignKey("TagAttributesId");

                    b.Navigation("TagAttributes");
                });

            modelBuilder.Entity("API.Entites.MangaUser", b =>
                {
                    b.HasOne("API.Entites.UserData", "Data")
                        .WithMany()
                        .HasForeignKey("DataId");

                    b.Navigation("Data");
                });

            modelBuilder.Entity("API.Entites.Relationship", b =>
                {
                    b.HasOne("API.Entites.Manga", null)
                        .WithMany("Relationships")
                        .HasForeignKey("MangaId");
                });

            modelBuilder.Entity("API.Entites.ScanlationGroup", b =>
                {
                    b.HasOne("API.Entites.User", "Leader")
                        .WithMany()
                        .HasForeignKey("LeaderId");

                    b.Navigation("Leader");
                });

            modelBuilder.Entity("API.Entites.TagAttributes", b =>
                {
                    b.HasOne("API.Entites.TagName", "Name")
                        .WithMany()
                        .HasForeignKey("NameTagNameId");

                    b.Navigation("Name");
                });

            modelBuilder.Entity("API.Entites.UserData", b =>
                {
                    b.HasOne("API.Entites.UserAttributes", "Attributes")
                        .WithMany()
                        .HasForeignKey("AttributesId");

                    b.Navigation("Attributes");
                });

            modelBuilder.Entity("API.Entites.UserRelationship", b =>
                {
                    b.HasOne("API.Entites.UserData", null)
                        .WithMany("Relationships")
                        .HasForeignKey("UserDataId");
                });

            modelBuilder.Entity("API.Entites.ChaptersRead", b =>
                {
                    b.Navigation("Data");
                });

            modelBuilder.Entity("API.Entites.Manga", b =>
                {
                    b.Navigation("Relationships");
                });

            modelBuilder.Entity("API.Entites.MangaAttributes", b =>
                {
                    b.Navigation("AltTitles");

                    b.Navigation("Tags");
                });

            modelBuilder.Entity("API.Entites.MangaChapter", b =>
                {
                    b.Navigation("Relationships");
                });

            modelBuilder.Entity("API.Entites.MangaChapters", b =>
                {
                    b.Navigation("results");
                });

            modelBuilder.Entity("API.Entites.MangaCollection", b =>
                {
                    b.Navigation("Mangas");
                });

            modelBuilder.Entity("API.Entites.User", b =>
                {
                    b.Navigation("Bio");
                });

            modelBuilder.Entity("API.Entites.UserData", b =>
                {
                    b.Navigation("Relationships");
                });
#pragma warning restore 612, 618
        }
    }
}
